[package]
name = "xswezan/orb"
description = "Create interactable Orbs easily!"
version = "1.0.0"
authors = ["xSwezan"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.1"
Signal = "sleitnick/signal@1.5.0"
# Promise = "evaera/promise@4.0.0"